### ISSUE TITLE
A little doubt about update function

### ISSUE THREAD

**Issue by frederikhors** [bkonkle/rust-example-caster-api#13]
I'll start a project soon and I would like to try Rust and SeaORM.

I found your code like this https://github.com/bkonkle/rust-example-caster-api/blob/main/libs/domains/src/shows/service.rs#L158-L168:

```rust
async fn update(&self, id: &str, input: &UpdateShowInput) -> Result<Show> {
    let query = model::Entity::find_by_id(id.to_owned());

    // Retrieve the existing Show
    let show = query.one(&*self.db).await?.ok_or_else(|| anyhow!("Unable to find Show with id: {}", id))?;

    let mut show: model::ActiveModel = show.into();

    //*************** My doubt starts here

    if let Some(title) = &input.title {
        show.title = Set(title.clone());
    }

    if let Some(summary) = &input.summary {
        show.summary = Set(Some(summary.clone()));
    }

    if let Some(picture) = &input.picture {
        show.picture = Set(Some(picture.clone()));
    }

    //*************** My doubt ends here

    let updated: Show = show.update(&*self.db).await?;

    Ok(updated)
}
```

What if for example `input.summary` is `None` because the user wants to "delete" the `summary`?

Maybe I'm wrong but in this case the `summary` content remains what was before this update, right?

**Comment by bkonkle** [comment]
You are absolutely right about this, and I solved it in another project with a double-Option. I can't remember how I translated that from the HTTP/JSON representation, though, so I ended my aforementioned livestream without covering it. I'll come back to this later this week and make some offline progress, and then talk about it on another livestream. 👍

**Comment by bkonkle** [comment]
Okay, I implemented a solution to this in my latest live stream here: https://www.youtube.com/watch?v=l2AMqV8eHY8

Thanks for the question!
