### ISSUE TITLE
Consider adding Caster API to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [bkonkle/rust-example-caster-api#2]
Hey @bkonkle, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by bkonkle** [comment]
Sorry I missed this earlier! Thank you for taking a look! I'd be happy to join the showcase. 😃 I'll submit a PR soon. 👍

**Comment by billy1624** [comment]
Hey @bkonkle, no worries! Thanks!
