### ISSUE TITLE
Question on user_factory for testing

### ISSUE THREAD

**Issue by rezmuh** [bkonkle/rust-example-caster-api#75]
I found this in the service_test of user domain:

https://github.com/bkonkle/rust-example-caster-api/blob/7f60ae0558ecf606ddc4b7e0756d382c1dd6e0b6/libs/domains/src/users/service_test.rs#L12

I cloned the project but could not find the definition of `create_user_with_username` function. Where is it defined? 

Thank you

**Comment by bkonkle** [comment]
Hi! This is a test file that was accidentally left behind. 😅 I forgot to delete that file when I moved the User Service tests to [libs/domains/src/users/tests/service_test.rs](https://github.com/bkonkle/rust-example-caster-api/blob/main/libs/domains/src/users/tests/service_test.rs).

The `user_factory` was leftover from a previous iteration. The last version of it [can be found here](https://github.com/bkonkle/rust-example-caster-api/blob/358093b5138820280b34edd7275a6443c9977607/libs/users/src/user_factory.rs). Afterwards, I removed the factories and went to using [the Dummy derive](https://github.com/bkonkle/rust-example-caster-api/blob/main/libs/domains/src/users/model.rs#L16) from the [fake](https://docs.rs/fake/latest/fake/) crate.

I'll remove the old files now. Thank you for letting me know!

**Comment by rezmuh** [comment]
Thanks!
